using System;

namespace KSPClone.SimCore
{
    /// <summary>
    /// Opaque identifier for a connected player. Generated by the server
    /// on connect; never reused within a session lifetime.
    /// </summary>
    public readonly record struct PlayerId(Guid Value)
    {
        public static PlayerId New() => new(Guid.NewGuid());
        public override string ToString() => Value.ToString("N");
    }
}