#nullable enable annotations

using System;

namespace KSPClone.SimCore
{
    /// <summary>
    /// Opaque identifier for a connected player. Generated by the server
    /// on connect; never reused within a session lifetime.
    /// </summary>
    public readonly struct PlayerId : IEquatable<PlayerId>
    {
        public Guid Value { get; }

        public PlayerId(Guid value) => Value = value;

        public static PlayerId New() => new(Guid.NewGuid());

        public bool Equals(PlayerId other) => Value.Equals(other.Value);
        public override bool Equals(object? obj) => obj is PlayerId p && Equals(p);
        public override int GetHashCode() => Value.GetHashCode();
        public override string ToString() => Value.ToString("N");

        public static bool operator ==(PlayerId a, PlayerId b) => a.Equals(b);
        public static bool operator !=(PlayerId a, PlayerId b) => !a.Equals(b);
    }
}
